# Generated by Django 2.2.9 on 2021-02-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolemaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('role_code', models.CharField(max_length=200)),
                ('can_read', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=True)),
                ('can_map', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=True)),
                ('entity_id', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rolemaster',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('pincode', models.BigIntegerField()),
                ('role', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('entity_id', models.IntegerField(unique=True)),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
