# Generated by Django 2.2.9 on 2021-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='entity_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
