# Generated by Django 2.2.9 on 2021-02-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_auto_20210226_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
